apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-sca
spec:
  selector:
    matchLabels:
      app: grafana
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
    spec:
      hostname: grafana-sca
      containers:
      - name: grafana
        image: grafana/grafana:latest
        env:
        - name: GF_PLUGIN_ALLOW_LOCAL_MODE
          value: "true"
        - name: GF_INSTALL_PLUGINS
          value: "marcusolsson-treemap-panel,grafana-piechart-panel,marcusolsson-csv-datasource,boazreicher-mosaicplot-panel"
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: grafana-sca-config
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-sca-data
          mountPath: /home/grafana/data/
      volumes:
      - name: grafana-sca-config
        configMap:
            name: grafana-sca-config
      - name: grafana-sca-data
        configMap:
            name: grafana-sca-data
