apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-stack-sca-1
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      hostname: redis-stack-sca-1
      containers:
      - name: redis
        image: redis/redis-stack-server:latest
        ports:
        - containerPort: 6379

